services:
  - type: web
    name: poltuda
    runtime: python
    buildCommand: pip install -r PoltuDa/requirements.txt
    startCommand: gunicorn --chdir PoltuDa/backend app:app
    plan: free
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.11
      - key: FLASK_ENV
        value: production
      - key: JWT_SECRET_KEY
        generateValue: true
      - key: SECRET_KEY
        generateValue: true