"""add admin provider and service management state

Revision ID: ba7363c1399b
Revises: cd032e1dc91d
Create Date: 2026-08-18 17:57:41.503293

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ba7363c1399b'
down_revision = 'cd032e1dc91d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('provider_services', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), nullable=False, server_default=sa.true()))
        batch_op.add_column(sa.Column('blocked_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('blocked_reason', sa.Text(), nullable=True))
        batch_op.alter_column('is_active', server_default=None)

    with op.batch_alter_table('providers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), nullable=False, server_default=sa.true()))
        batch_op.add_column(sa.Column('blocked_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('blocked_reason', sa.Text(), nullable=True))
        batch_op.alter_column('is_active', server_default=None)

    with op.batch_alter_table('services', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), nullable=False, server_default=sa.true()))
        batch_op.add_column(sa.Column('display_order', sa.Integer(), nullable=False, server_default='0'))
        batch_op.add_column(sa.Column('display_group', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('icon_key', sa.String(length=120), nullable=True))
        batch_op.alter_column('is_active', server_default=None)
        batch_op.alter_column('display_order', server_default=None)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('services', schema=None) as batch_op:
        batch_op.drop_column('icon_key')
        batch_op.drop_column('display_group')
        batch_op.drop_column('display_order')
        batch_op.drop_column('is_active')

    with op.batch_alter_table('providers', schema=None) as batch_op:
        batch_op.drop_column('blocked_reason')
        batch_op.drop_column('blocked_at')
        batch_op.drop_column('is_active')

    with op.batch_alter_table('provider_services', schema=None) as batch_op:
        batch_op.drop_column('blocked_reason')
        batch_op.drop_column('blocked_at')
        batch_op.drop_column('is_active')

    # ### end Alembic commands ###
