"""encrypt provider and user phone/whatsapp columns

Revision ID: cd032e1dc91d
Revises: dbc64a07cde3
Create Date: 2026-08-18 03:26:20.091371

NOTE: this only changes the column type. It does not re-encrypt any existing
plaintext rows. Safe here because no real phone/whatsapp data exists yet; if
run against a database with pre-existing plaintext values, those values must
be encrypted (e.g. via a one-off data migration) before/along with this.
"""
import app.crypto
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cd032e1dc91d'
down_revision = 'dbc64a07cde3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('providers', schema=None) as batch_op:
        batch_op.alter_column('phone',
               existing_type=sa.VARCHAR(length=40),
               type_=app.crypto.EncryptedString(),
               existing_nullable=True)
        batch_op.alter_column('whatsapp',
               existing_type=sa.VARCHAR(length=40),
               type_=app.crypto.EncryptedString(),
               existing_nullable=True)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('phone',
               existing_type=sa.VARCHAR(length=40),
               type_=app.crypto.EncryptedString(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('phone',
               existing_type=app.crypto.EncryptedString(),
               type_=sa.VARCHAR(length=40),
               existing_nullable=True)

    with op.batch_alter_table('providers', schema=None) as batch_op:
        batch_op.alter_column('whatsapp',
               existing_type=app.crypto.EncryptedString(),
               type_=sa.VARCHAR(length=40),
               existing_nullable=True)
        batch_op.alter_column('phone',
               existing_type=app.crypto.EncryptedString(),
               type_=sa.VARCHAR(length=40),
               existing_nullable=True)

    # ### end Alembic commands ###
