services:
  - type: web
    name: tedile
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt && flask db upgrade"
    startCommand: "gunicorn --bind 0.0.0.0:$PORT \"app:create_app()\""
    envVars:
      - key: PYTHON_VERSION
        value: "3.12.10"
      - key: FLASK_DEBUG
        value: "false"
      - key: APP_ENV
        value: "production"
      - key: FLASK_APP
        value: "app.py"
      - key: SECRET_KEY
        sync: false
      - key: ENCRYPTION_KEY
        sync: false
      - key: DATABASE_URL
        sync: false
      - key: AWS_REGION
        value: "ap-south-1"
      - key: S3_BUCKET_NAME
        sync: false
      - key: AWS_ACCESS_KEY_ID
        sync: false
      - key: AWS_SECRET_ACCESS_KEY
        sync: false
