services:
  - type: web
    name: bengal-learning-center
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn app:app"
    envVars:
      - key: FLASK_DEBUG
        value: "false"
      - key: SECRET_KEY
        sync: false
      - key: DATABASE_URL
        sync: false
      - key: AWS_REGION
        value: "ap-south-1"
      - key: S3_BUCKET_NAME
        sync: false
      - key: AWS_ACCESS_KEY_ID
        sync: false
      - key: AWS_SECRET_ACCESS_KEY
        sync: false
